apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
spec:
  params:
    - name: name
      type: string
      description: who to greet
  steps:
    - name: say-hello
      image: alpine
      script: |
        echo "Hello $(params.name)!"
