apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  params:
    - name: name
      type: string
      description: who to greet
  tasks:
    - name: say-hello
      taskSpec:
        steps:
          - name: echo-hello
            image: ubuntu
            script: |
              echo "Hello $(params.name)!"
