apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  params:
    - name: name
      type: string
      description: who to greet
  tasks:
    - name: say-hello
      params:
        - name: name
          value: $(params.name)
      taskSpec:
        params:
          - name: name
            default: "GitHub Actions"
        steps:
          - name: echo-hello
            image: ubuntu
            script: |
              echo "Hello $(params.name)!"
